/**
 * End-to-end composition proof for Manifest 2.0.
 *
 * Every other suite in this repo verifies ONE seam: log-core proves
 * `verifyManifestChain` walks root → cert → manifest; `bundle-manifest.test.ts`
 * proves `verifyBundleTrustChain` adds the two bundle-level bindings;
 * `policy-gating.test.ts` proves each heuristic honours a policy handed to it.
 * Nothing proved that a bundle produced the way a recorder produces one — real
 * ed25519 keys, a real hash chain, a real ZIP, the real loader — survives the
 * whole pipeline.
 *
 * That gap matters most for **validation check 2**. It used to compare
 * `manifest_sig` across sessions for equality; it now claims to walk
 * root → course cert → manifest → session entirely offline. If that walk is
 * wrong the failure mode is a system that reports genuine bundles as forged, or
 * forged bundles as genuine.
 *
 * Every case here therefore goes through `buildTestBundle` → a real ZIP →
 * `loadBundle` → `runValidation` / `buildIndex` + `runHeuristics`, with no
 * stubbing of the signature path, and asserts the specific check **id** and
 * **status** rather than "validation failed". A test that passes because
 * something else broke is worse than no test.
 *
 * Determinism: all keys come from fixed seeds via `buildTrustChainKeys`, all
 * walls/`t` values are generated by `buildTestBundle` from a fixed epoch, and
 * nothing here reads `Date.now()` or `Math.random()`.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import * as ed from '@noble/ed25519';
import { sha512 } from '@noble/hashes/sha2.js';
import {
  sha256Hex,
  signManifest,
  signCourseCert,
  verifyManifest,
  verifyCourseCert,
  resolveCapturePolicy,
  isEventKindCaptured,
  DEFAULT_CAPTURE_POLICY,
} from '@provenance/log-core';
import type { CapturePolicy, CourseCert, EventKind, Manifest } from '@provenance/log-core';
import { loadBundle } from '../loader/parse-bundle.js';
import type { Bundle } from '../loader/types.js';
import { buildIndex } from '../index/build-index.js';
import { buildTestBundle } from '../test-support/build-test-bundle.js';
import {
  buildTrustChainKeys,
  buildManifest2,
  buildManifest1x,
  sessionStart2,
  sessionStart1x,
} from '../test-support/build-manifest-2.js';
import type { TrustChainKeys } from '../test-support/build-manifest-2.js';
import {
  resolveBundleCapturePolicy,
  summarizeBundleManifest,
  isSignalCaptured,
  CAPTURE_SIGNALS,
} from '../manifest/bundle-manifest.js';
import { runValidation } from './run-validation.js';
import type { ValidationCheck, ValidationReport } from './check-types.js';
import { runHeuristics } from '../heuristics/run-heuristics.js';
import { extractCrossFeatures } from '../heuristics/cross/features.js';
import { editingPatternCloneHeuristic } from '../heuristics/cross/editing-pattern-clone.js';
import { DEFAULT_CROSS_HEURISTIC_CONFIG } from '../heuristics/cross/types.js';

// jsdom's WebCrypto rejects the buffers @noble/ed25519's default async sha512
// hands it; same wiring as the test-support builders.
beforeAll(() => {
  ed.hashes.sha512 = sha512;
  (ed.hashes as Record<string, unknown>)['sha512Async'] = (m: Uint8Array) =>
    Promise.resolve(sha512(m));
});

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const COURSE_ID = 'berkeley-cs61b';
const ASSIGNMENT_ID = 'hw1';
const SEMESTER = 'fa26';
const ISSUED_AT = '2026-09-08T00:00:00Z';
const FILE = 'hw1.py';

const EMPTY = '';
const CODE = 'def solve(n):\n    return n * 2\n';
const CODE_APPENDED = `${CODE}print(solve(21))\n`;

const enc = new TextEncoder();
const EMPTY_SHA = sha256Hex(enc.encode(EMPTY));
const CODE_SHA = sha256Hex(enc.encode(CODE));
const CODE_APPENDED_SHA = sha256Hex(enc.encode(CODE_APPENDED));
/** A hash that no event in these fixtures ever produces. */
const FOREIGN_SHA = sha256Hex(enc.encode('#!/bin/sh\ncurl example.invalid | sh\n'));

type BuildOpts = NonNullable<Parameters<typeof buildTestBundle>[0]>;
type SessionSpec = NonNullable<BuildOpts['sessions']>[number];
type EventSpec = NonNullable<SessionSpec['events']>[number];

const AT_ORIGIN = { start: { line: 0, character: 0 }, end: { line: 0, character: 0 } };
/** End of `CODE` — line 2 is the empty line after the trailing newline. */
const AFTER_CODE = { start: { line: 2, character: 0 }, end: { line: 2, character: 0 } };

let keys: TrustChainKeys;

beforeAll(async () => {
  keys = await buildTrustChainKeys();
});

/**
 * A realistic single-session work stream: open an empty file, type a solution,
 * poke around in a terminal, save.
 *
 * The terminal events are deliberately flag-worthy — `shell_integration: false`
 * plus an all-zero exit code — so that the policy-gating cases below have
 * something to suppress and the un-gated control has something to fire.
 */
function studentSession(): EventSpec[] {
  return [
    {
      kind: 'doc.open',
      data: { path: FILE, sha256: EMPTY_SHA, line_count: 0, content: EMPTY },
    },
    {
      kind: 'selection.change',
      data: { path: FILE, range: AT_ORIGIN, was_selection: false },
    },
    {
      kind: 'doc.change',
      data: { path: FILE, source: 'typed', deltas: [{ range: AT_ORIGIN, text: CODE }] },
    },
    { kind: 'focus.change', data: { gained: true } },
    {
      kind: 'terminal.open',
      data: { terminal_id: 't1', shell: '/bin/zsh', shell_integration: false },
    },
    {
      kind: 'terminal.command',
      data: { terminal_id: 't1', command: 'python hw1.py', exit_code: 0 },
    },
    { kind: 'doc.save', data: { path: FILE, sha256: CODE_SHA } },
    { kind: 'session.end', data: { reason: 'window_closed' } },
  ];
}

/** A continuation session: reopen the saved file, append a line, save again. */
function continuationSession(): EventSpec[] {
  return [
    {
      kind: 'doc.open',
      data: { path: FILE, sha256: CODE_SHA, line_count: 2, content: CODE },
    },
    {
      kind: 'doc.change',
      data: {
        path: FILE,
        source: 'typed',
        deltas: [{ range: AFTER_CODE, text: 'print(solve(21))\n' }],
      },
    },
    { kind: 'doc.save', data: { path: FILE, sha256: CODE_APPENDED_SHA } },
    { kind: 'session.end', data: { reason: 'window_closed' } },
  ];
}

/**
 * A stream that trips all three terminal-dependent heuristics under a 1.x
 * bundle: `shell_integration_disabled` (terminal.open with the flag off),
 * `no_intermediate_errors` (its shell-integration-disabled degradation), and
 * `terminal_active_during_external_change` (a terminal open before an external
 * write).
 */
function terminalHeavySession(): EventSpec[] {
  return [
    {
      kind: 'doc.open',
      data: { path: FILE, sha256: EMPTY_SHA, line_count: 0, content: EMPTY },
    },
    {
      kind: 'doc.change',
      data: { path: FILE, source: 'typed', deltas: [{ range: AT_ORIGIN, text: CODE }] },
    },
    {
      kind: 'terminal.open',
      data: { terminal_id: 't1', shell: '/bin/zsh', shell_integration: false },
    },
    {
      kind: 'terminal.command',
      data: { terminal_id: 't1', command: 'python hw1.py', exit_code: 0 },
    },
    {
      kind: 'fs.external_change',
      data: {
        path: FILE,
        old_hash: CODE_SHA,
        new_hash: FOREIGN_SHA,
        diff_size: 120,
        operation: 'modify',
      },
    },
    { kind: 'session.end', data: { reason: 'window_closed' } },
  ];
}

const TERMINAL_HEURISTICS = [
  'shell_integration_disabled',
  'no_intermediate_errors',
  'terminal_active_during_external_change',
] as const;

/**
 * Mirror of the recorder's single capture choke point
 * (`packages/recorder/src/session/session-host.ts`): suppression happens BEFORE
 * `seq` is allocated, so a dropped event consumes no seq and leaves no hole for
 * check 4 to read as a deleted entry. `buildTestBundle` numbers whatever list it
 * is handed contiguously from 0, so filtering here reproduces exactly the stream
 * a policy-configured recorder would have written.
 */
function applyCapturePolicy(events: EventSpec[], policy: CapturePolicy): EventSpec[] {
  return events.filter((e) => isEventKindCaptured(e.kind as EventKind, policy));
}

async function buildBundle(opts: BuildOpts): Promise<Bundle> {
  const { zipBuffer } = await buildTestBundle({
    assignmentId: ASSIGNMENT_ID,
    semester: SEMESTER,
    ...opts,
  });
  const loaded = await loadBundle(new Blob([zipBuffer]), 'e2e.zip');
  if (!loaded.ok) throw new Error(`bundle load failed: ${JSON.stringify(loaded.error)}`);
  return loaded.value;
}

/** A complete, submittable 2.0 bundle carrying `manifest` in every session.start. */
async function build20Bundle(
  manifest: Manifest,
  sessions: SessionSpec[] = [{ events: studentSession() }],
): Promise<Bundle> {
  const start = sessionStart2(manifest);
  return buildBundle({
    sessions: sessions.map((s) => ({
      ...s,
      sessionStart: { ...start, ...(s.sessionStart ?? {}) },
    })),
    submissionFiles: [{ path: FILE, status: 'present', content: CODE }],
  });
}

function check(report: ValidationReport, id: string): ValidationCheck {
  const found = report.checks.find((c) => c.id === id);
  if (found === undefined) throw new Error(`no check with id ${id}`);
  return found;
}

function statuses(report: ValidationReport): Record<string, string> {
  return Object.fromEntries(report.checks.map((c) => [c.id, c.status]));
}

const ALL_PASS = {
  manifest_sig: 'pass',
  session_binding: 'pass',
  chain_integrity: 'pass',
  seq_gaps: 'pass',
  monotonic_t: 'pass',
  monotonic_wall: 'pass',
  doc_save_hashes: 'pass',
  submitted_code_match: 'pass',
};

/**
 * The links that must stay green while a trust-chain tamper case fails check 2.
 * Asserting these is what makes each case fail for the RIGHT reason: a bundle
 * whose hash chain also broke would "fail validation" for a completely
 * different one.
 */
function expectOnlySessionBindingFailed(report: ValidationReport): void {
  expect(statuses(report)).toEqual({ ...ALL_PASS, session_binding: 'fail' });
}

// ---------------------------------------------------------------------------
// 1. A valid 2.0 bundle passes all eight checks, with a real chain walk.
// ---------------------------------------------------------------------------

describe('a genuine Manifest 2.0 bundle', () => {
  it('passes all eight validation checks, check 2 walking root → cert → manifest → session', async () => {
    const manifest = await buildManifest2({
      keys,
      courseId: COURSE_ID,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
      policy: { capture: { selection_change: true, focus_change: true, terminal: true } },
    });
    const bundle = await build20Bundle(manifest);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expect(statuses(report)).toEqual(ALL_PASS);
    expect(report.overall).toBe('pass');

    // Check 2 must have taken the CHAIN path, not the legacy sig-equality one.
    const binding = check(report, 'session_binding');
    expect(binding.detail).toContain('Trust chain verified offline');
    expect(binding.detail).toContain(`root → course_cert (${COURSE_ID}) → manifest`);
    expect(binding.detail).toContain(`certificate valid at issue time (${ISSUED_AT})`);

    const summary = await summarizeBundleManifest(bundle, keys.rootPubkeyHex);
    expect(summary.format_version).toBe('2.0');
    expect(summary.trust_chain).toBe('verified');
    expect(summary.cert?.course_pubkey).toBe(keys.coursePubkeyHex);
    expect(summary.cert?.in_window).toBe(true);
    expect(summary.disabled_signals).toEqual([]);
  });

  it('reports check 2 as skipped — never pass — when no root key is configured', async () => {
    // The chain walk genuinely consumes the root key. Without one there is no
    // statement to make, and inventing either verdict would be worse than none.
    const manifest = await buildManifest2({ keys, courseId: COURSE_ID, filesUnderReview: [FILE] });
    const bundle = await build20Bundle(manifest);

    const report = await runValidation(bundle);

    expect(check(report, 'session_binding').status).toBe('skipped');
    expect(check(report, 'session_binding').detail).toContain('no root public key');
    expect(report.overall).toBe('warn');
  });
});

// ---------------------------------------------------------------------------
// 2. A 1.x bundle still passes, on the legacy sig-equality path.
//    1.x support is PERMANENT — this is the regression guard for archived
//    submissions (program spec §9).
// ---------------------------------------------------------------------------

describe('a 1.x bundle', () => {
  it('passes all eight checks via the legacy sig-equality path, even with a root key configured', async () => {
    const bundle = await buildBundle({
      sessions: [{ events: studentSession() }, { events: continuationSession() }],
      submissionFiles: [{ path: FILE, status: 'present', content: CODE_APPENDED }],
    });

    // This fixture is a PRE-2.0 recorder: it wrote no `data.manifest` at all.
    // That is a property of this fixture, not of 1.x bundles in general — a
    // current recorder embeds the manifest whatever its version, which is the
    // case the sibling test below covers.
    expect(bundle.sessions.every((s) => s.firstEvent.data.manifest === undefined)).toBe(true);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expect(statuses(report)).toEqual(ALL_PASS);
    expect(report.overall).toBe('pass');

    const binding = check(report, 'session_binding');
    expect(binding.detail).toBe('All 2 sessions share the same manifest_sig.');
    expect(binding.detail).not.toContain('Trust chain');

    const summary = await summarizeBundleManifest(bundle, keys.rootPubkeyHex);
    expect(summary.format_version).toBe('1.x');
    expect(summary.trust_chain).toBe('legacy');
    expect(summary.disabled_signals).toEqual([]);
    expect(summary.heartbeat_interval_ms).toBe(30_000);
  });

  it('passes all eight checks when a CURRENT recorder embeds the 1.x manifest', async () => {
    // The grandfathering case, and the regression this suite previously missed:
    // a course still issuing 1.x manifests whose students have updated to a
    // recorder that emits `session.start.data.manifest` unconditionally.
    //
    // The reader must decide legacy-vs-2.0 by the embedded manifest's
    // `format_version`, never by its presence. Reading presence as a 2.0 claim
    // sends this bundle into the chain walk, which refuses at step 0 with
    // `not_manifest_2_0` — failing check 2 for every submission in the course.
    const manifest1x = await buildManifest1x({
      keys,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
    });
    const start = sessionStart1x(manifest1x);
    const bundle = await buildBundle({
      sessions: [
        { events: studentSession(), sessionStart: start },
        { events: continuationSession(), sessionStart: start },
      ],
      submissionFiles: [{ path: FILE, status: 'present', content: CODE_APPENDED }],
    });

    // The fixture really is what a current recorder writes: manifest embedded,
    // 1.x, and bound by manifest_sig.
    expect(bundle.sessions.every((s) => s.firstEvent.data.manifest !== undefined)).toBe(true);
    expect(bundle.sessions[0]!.firstEvent.data.manifest_sig).toBe(manifest1x.sig);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expect(statuses(report)).toEqual(ALL_PASS);
    expect(report.overall).toBe('pass');

    // Legacy path, not the chain path — and emphatically not `not_manifest_2_0`.
    const binding = check(report, 'session_binding');
    expect(binding.detail).toBe('All 2 sessions share the same manifest_sig.');
    expect(binding.detail).not.toContain('Trust chain');

    const summary = await summarizeBundleManifest(bundle, keys.rootPubkeyHex);
    expect(summary.format_version).toBe('1.x');
    expect(summary.trust_chain).toBe('legacy');
    expect(summary.trust_chain_detail).toBeNull();
    expect(summary.course_id).toBeNull();
    expect(summary.disabled_signals).toEqual([]);
    expect(summary.heartbeat_interval_ms).toBe(30_000);

    // A 1.x manifest signs no policy, so the resolved policy is the DEFAULT one
    // and its source is `default` — not `unverified_manifest`, which would be
    // the same presence-vs-version confusion one layer down.
    const policy = resolveBundleCapturePolicy(bundle);
    expect(policy.source).toBe('default');
    expect(policy.effective).toEqual(DEFAULT_CAPTURE_POLICY);
    expect(policy.claimedDisabledSignals).toEqual([]);
    for (const signal of CAPTURE_SIGNALS) {
      expect(isSignalCaptured(bundle, signal)).toBe(true);
    }

    // An unverifiable 1.x chain must never be stamped `verified`: the trust
    // stamp gates whether a signed policy is honoured, and there is no verified
    // signature here to honour one from.
    expect(bundle.capturePolicyTrust).toBe('unverified');
  });

  it('takes the legacy path when only SOME sessions embed the 1.x manifest', async () => {
    // A student who updated their recorder mid-assignment: the earlier session
    // predates the embedding, the later one carries the manifest. No session
    // claims 2.0, so there is no chain to walk and sig-equality is the whole
    // statement available — the same answer both sessions would have got alone.
    const manifest1x = await buildManifest1x({
      keys,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
    });
    const bundle = await buildBundle({
      sessions: [
        // Pre-update: manifest_sig only, no embedded manifest.
        { events: studentSession(), sessionStart: { manifest_sig: manifest1x.sig } },
        // Post-update: the same manifest, now embedded.
        { events: continuationSession(), sessionStart: sessionStart1x(manifest1x) },
      ],
      submissionFiles: [{ path: FILE, status: 'present', content: CODE_APPENDED }],
    });

    expect(bundle.sessions[0]!.firstEvent.data.manifest).toBeUndefined();
    expect(bundle.sessions[1]!.firstEvent.data.manifest).toBeDefined();

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expect(statuses(report)).toEqual(ALL_PASS);
    expect(check(report, 'session_binding').detail).toBe(
      'All 2 sessions share the same manifest_sig.',
    );
    expect(resolveBundleCapturePolicy(bundle).source).toBe('default');
  });

  it('still fails check 2 when two sessions bind to different assignment manifests', async () => {
    const bundle = await buildBundle({
      sessions: [
        { events: studentSession() },
        {
          events: continuationSession(),
          sessionStart: { manifest_sig: 'a-different-assignment' },
        },
      ],
      submissionFiles: [{ path: FILE, status: 'present', content: CODE_APPENDED }],
    });

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expectOnlySessionBindingFailed(report);
    expect(check(report, 'session_binding').detail).toContain(
      'was started against a different assignment manifest',
    );
  });
});

// ---------------------------------------------------------------------------
// 3. Tampering is caught per link, each failing for the right reason.
// ---------------------------------------------------------------------------

describe('trust-chain tampering', () => {
  it('rejects a course_cert the root never signed', async () => {
    // Same course key, but the certificate is signed by a root the analyzer
    // does not trust.
    const rogueRoot = await buildTrustChainKeys(0x99, 0x22);
    const manifest = await buildManifest2({
      keys: rogueRoot,
      courseId: COURSE_ID,
      filesUnderReview: [FILE],
    });
    const bundle = await build20Bundle(manifest);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expectOnlySessionBindingFailed(report);
    expect(check(report, 'session_binding').detail).toContain(
      'course_cert does not verify against the root public key',
    );
  });

  it('rejects a manifest signed by a course key the root never certified', async () => {
    // The certificate is genuine (root-signed, vouching for the real course
    // key) — but the manifest payload was signed by a different key entirely.
    // Step 1 passes; step 2 must catch it.
    const rogueCourse = await buildTrustChainKeys(0x11, 0x77);
    const manifest = await buildManifest2({
      keys: { ...keys, coursePrivkey: rogueCourse.coursePrivkey },
      courseId: COURSE_ID,
      filesUnderReview: [FILE],
    });
    expect(manifest.course_cert?.course_pubkey).toBe(keys.coursePubkeyHex);
    await expect(
      verifyCourseCert(manifest.course_cert as CourseCert, keys.rootPubkeyHex),
    ).resolves.toMatchObject({ ok: true });

    const bundle = await build20Bundle(manifest);
    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expectOnlySessionBindingFailed(report);
    expect(check(report, 'session_binding').detail).toContain(
      'manifest payload does not verify against the certified course public key',
    );
  });

  it('rejects a manifest whose course_id disagrees with its certificate', async () => {
    // 61B's key signing a manifest that claims to be 61C. Both signatures are
    // genuine; only comparing the two ids catches it.
    const manifest = await buildManifest2({
      keys,
      courseId: 'berkeley-cs61c',
      certCourseId: COURSE_ID,
      filesUnderReview: [FILE],
    });
    const bundle = await build20Bundle(manifest);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expectOnlySessionBindingFailed(report);
    expect(check(report, 'session_binding').detail).toContain(
      `manifest course_id berkeley-cs61c does not match certificate course_id ${COURSE_ID}`,
    );
  });

  it('rejects a bundle whose sessions disagree on manifest version', async () => {
    // One session carries a genuine 2.0 manifest, another a genuine 1.x one.
    // Some session claims 2.0, so the bundle is held to the 2.0 contract and
    // the chain is walked against the 2.0 manifest — the 1.x session must not
    // get to drag the walk onto a manifest that has no chain. The 1.x session
    // then fails the sig binding, which is the honest cause: it was keyed by a
    // different manifest entirely.
    const manifest2 = await buildManifest2({
      keys,
      courseId: COURSE_ID,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
    });
    const manifest1x = await buildManifest1x({
      keys,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
    });

    // 1.x session FIRST, so a reader that simply took the first embedded
    // manifest would walk the 1.x one and report `not_manifest_2_0`.
    const bundle = await buildBundle({
      sessions: [
        { events: studentSession(), sessionStart: sessionStart1x(manifest1x) },
        { events: continuationSession(), sessionStart: sessionStart2(manifest2) },
      ],
      submissionFiles: [{ path: FILE, status: 'present', content: CODE_APPENDED }],
    });

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expectOnlySessionBindingFailed(report);
    const binding = check(report, 'session_binding');
    expect(binding.detail).toContain(`recorded manifest_sig ${manifest1x.sig.slice(0, 16)}…`);
    expect(binding.detail).toContain('but carries a manifest signed');
    expect(binding.detail).not.toContain('not 2.0');
    expect(binding.supportingSeqs).toEqual([{ sessionId: bundle.sessions[0]!.sessionId, seq: 0 }]);
  });

  it('rejects a policy block edited after signing — the student off-switch attempt', async () => {
    const genuine = await buildManifest2({
      keys,
      courseId: COURSE_ID,
      filesUnderReview: [FILE],
      policy: { capture: { selection_change: true, focus_change: true, terminal: true } },
    });

    // Control: the untouched manifest verifies. Everything below differs from
    // this by exactly one boolean inside `policy`.
    const cleanReport = await runValidation(await build20Bundle(genuine), {
      rootPubkeyHex: keys.rootPubkeyHex,
    });
    expect(statuses(cleanReport)).toEqual(ALL_PASS);

    const edited: Manifest = {
      ...genuine,
      policy: { capture: { selection_change: true, focus_change: true, terminal: false } },
    };
    const bundle = await build20Bundle(edited);
    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expectOnlySessionBindingFailed(report);
    expect(check(report, 'session_binding').detail).toContain(
      'manifest payload does not verify against the certified course public key',
    );
    // And the summary must not present the edited policy as course-sanctioned.
    const summary = await summarizeBundleManifest(bundle, keys.rootPubkeyHex);
    expect(summary.trust_chain).toBe('invalid');
    expect(summary.trust_chain_detail).toContain('certified course public key');
    expect(summary.cert?.in_window).toBe(false);
    expect(summary.cert?.window_reason).toBe('unverified');
  });

  it("rejects a session whose manifest_sig is not the embedded manifest's sig", async () => {
    // `manifest_sig` is the HKDF input keying material for the session keypair,
    // so this equality is what binds the VERIFIED manifest to the key that
    // signed this session's checkpoints and the bundle seal. The override is
    // applied before chaining, so the hash chain stays intact and check 2 is
    // the only thing that can catch it.
    const manifest = await buildManifest2({ keys, courseId: COURSE_ID, filesUnderReview: [FILE] });
    const strangerSig = 'b'.repeat(128);
    const bundle = await build20Bundle(manifest, [
      { events: studentSession() },
      { events: continuationSession(), sessionStart: { manifest_sig: strangerSig } },
    ]);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });

    expect(statuses(report)).toEqual({
      ...ALL_PASS,
      session_binding: 'fail',
      // The second session ends at CODE_APPENDED, which is not what was submitted.
      submitted_code_match: 'fail',
    });
    const binding = check(report, 'session_binding');
    expect(binding.detail).toContain(`recorded manifest_sig ${strangerSig.slice(0, 16)}…`);
    expect(binding.detail).toContain('but carries a manifest signed');
    expect(binding.supportingSeqs).toEqual([{ sessionId: bundle.sessions[1]!.sessionId, seq: 0 }]);
  });
});

// ---------------------------------------------------------------------------
// 4. The 1.x downgrade attack is neutralised.
//    Every signature verifies individually, so the defence cannot be a
//    signature check. It is the parse: 2.0-only fields do not survive being
//    read off a manifest that declares itself 1.x, so the downgrade buys the
//    student a plain 1.x bundle and nothing else.
// ---------------------------------------------------------------------------

describe('the 1.x downgrade attack', () => {
  /**
   * A genuine 1.x manifest (signed over the four 1.x fields only) with a real
   * root-signed certificate stapled on, plus an invented `policy` and the 2.0
   * capability fields — none of which the 1.x signature covers.
   */
  async function buildDowngradeManifest(): Promise<{ manifest: Manifest; cert: CourseCert }> {
    const legacyPayload = {
      assignment_id: ASSIGNMENT_ID,
      semester: SEMESTER,
      issued_at: ISSUED_AT,
      files_under_review: [FILE],
    };
    const sig = await signManifest(legacyPayload, keys.coursePrivkey);

    const certPayload: Omit<CourseCert, 'root_sig'> = {
      course_id: COURSE_ID,
      course_pubkey: keys.coursePubkeyHex,
      valid_from: '2026-08-20',
      valid_until: '2027-01-15',
    };
    const cert: CourseCert = {
      ...certPayload,
      root_sig: await signCourseCert(certPayload, keys.rootPrivkey),
    };

    return {
      cert,
      manifest: {
        // No `format_version` at all — this is what a 1.x manifest looks like.
        ...legacyPayload,
        sig,
        course_id: COURSE_ID,
        collaboration: 'solo',
        submission: 'bundle',
        scope: 'directory',
        // The prize: capture switched off by a block nobody signed.
        policy: { capture: { selection_change: false, focus_change: false, terminal: false } },
        course_cert: cert,
      },
    };
  }

  it('has every individual signature verify — which is exactly why step 0 must exist', async () => {
    const { manifest, cert } = await buildDowngradeManifest();

    await expect(verifyCourseCert(cert, keys.rootPubkeyHex)).resolves.toMatchObject({ ok: true });
    await expect(verifyManifest(manifest, keys.coursePubkeyHex)).resolves.toMatchObject({
      ok: true,
    });
  });

  it('is treated as the 1.x bundle it declares itself to be, gaining nothing', async () => {
    // This assertion was previously `session_binding: 'fail'`, on the grounds
    // that step 0 of the chain walk refuses `not_manifest_2_0`. That verdict was
    // unreachable without also failing every HONEST 1.x bundle a current
    // recorder writes, because reaching step 0 at all required treating the mere
    // PRESENCE of `data.manifest` as a 2.0 claim — and a current recorder embeds
    // 1.x manifests too. A refusal that fires on 100% of a grandfathered
    // course's submissions is not a detection, so the check is now made on
    // `format_version` and this bundle takes the legacy path.
    //
    // Nothing is conceded by that. The attack is defeated one layer down, where
    // it always was: `parseManifestValue` drops `course_id`, `policy`, and
    // `course_cert` from any manifest below 2.0, so the stapled-on fields never
    // reach a reader. The manifest is treated as exactly what it declares —
    // a 1.x manifest — and a 1.x manifest confers nothing.
    const { manifest } = await buildDowngradeManifest();
    const bundle = await build20Bundle(manifest);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    expect(statuses(report)).toEqual(ALL_PASS);

    const binding = check(report, 'session_binding');
    expect(binding.detail).toBe('Single session; binding trivially consistent.');
    // Emphatically NOT the old step-0 refusal, which cost more than it caught.
    expect(binding.detail).not.toContain('not 2.0');
    expect(binding.detail).not.toContain('signature');

    // What the attacker actually wanted, and did not get: none of the unsigned
    // 2.0 fields survive, and the chain is never reported as verified.
    const summary = await summarizeBundleManifest(bundle, keys.rootPubkeyHex);
    expect(summary.format_version).toBe('1.x');
    expect(summary.trust_chain).toBe('legacy');
    expect(summary.course_id).toBeNull();
    expect(summary.cert).toBeNull();
    expect(summary.disabled_signals).toEqual([]);
    expect(bundle.capturePolicyTrust).toBe('unverified');
  });

  it('does not hand the student the capture off-switch it was reaching for', async () => {
    const { manifest } = await buildDowngradeManifest();
    const bundle = await build20Bundle(manifest, [{ events: terminalHeavySession() }]);

    // The unsigned `policy` never becomes an effective policy: at 1.x the field
    // is not part of the manifest schema at all, so it is dropped on parse.
    const resolved = resolveBundleCapturePolicy(bundle);
    expect(resolved.disabledSignals).toEqual([]);
    expect(isSignalCaptured(bundle, 'terminal')).toBe(true);

    // …and the terminal heuristics it was meant to silence still fire.
    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    const fired = new Set(
      runHeuristics(buildIndex(bundle), bundle, report).map((f) => f.heuristic),
    );
    for (const id of TERMINAL_HEURISTICS) expect(fired).toContain(id);
  });
});

// ---------------------------------------------------------------------------
// 5. The absence-vs-disabled rule holds end to end.
// ---------------------------------------------------------------------------

describe('a signed policy that disables terminal capture', () => {
  const TERMINAL_OFF = { capture: { selection_change: true, focus_change: true, terminal: false } };

  async function terminalOffManifest(): Promise<Manifest> {
    return buildManifest2({
      keys,
      courseId: COURSE_ID,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
      policy: TERMINAL_OFF,
    });
  }

  /** Build the bundle a policy-honouring recorder would actually have written. */
  async function buildSuppressedBundle(): Promise<{ manifest: Manifest; bundle: Bundle }> {
    const manifest = await terminalOffManifest();
    const policy = resolveCapturePolicy(manifest.policy);
    expect(policy.terminal).toBe(false);

    const bundle = await buildBundle({
      sessions: [
        {
          sessionStart: sessionStart2(manifest),
          events: applyCapturePolicy(terminalHeavySession(), policy),
        },
      ],
    });
    return { manifest, bundle };
  }

  it('is proven signed: check 2 verifies and the summary names the disabled signal', async () => {
    const { bundle } = await buildSuppressedBundle();

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    expect(check(report, 'session_binding').status).toBe('pass');

    const summary = await summarizeBundleManifest(bundle, keys.rootPubkeyHex);
    expect(summary.trust_chain).toBe('verified');
    expect(summary.disabled_signals).toEqual(['terminal']);
  });

  it('makes the terminal heuristics not-applicable, where a 1.x bundle fires all three', async () => {
    // Control: the identical event stream under a 1.x bundle. If this half stops
    // producing flags the gated half below proves nothing.
    const legacy = await buildBundle({ sessions: [{ events: terminalHeavySession() }] });
    const legacyReport = await runValidation(legacy);
    const legacyFired = new Set(
      runHeuristics(buildIndex(legacy), legacy, legacyReport).map((f) => f.heuristic),
    );
    for (const id of TERMINAL_HEURISTICS) expect(legacyFired).toContain(id);

    const { bundle } = await buildSuppressedBundle();
    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    const gatedFired = new Set(
      runHeuristics(buildIndex(bundle), bundle, report).map((f) => f.heuristic),
    );
    for (const id of TERMINAL_HEURISTICS) expect(gatedFired).not.toContain(id);
  });

  it('gates on the policy itself, not merely on the absence of terminal events', async () => {
    // A recorder that ignored the policy (a stale build, a hostile port) would
    // still emit terminal events. The analyzer must refuse to reason about them
    // rather than reading them as evidence the course said not to collect.
    const manifest = await terminalOffManifest();
    const bundle = await buildBundle({
      sessions: [{ sessionStart: sessionStart2(manifest), events: terminalHeavySession() }],
    });
    expect(buildIndex(bundle).ordered.some((e) => e.kind.startsWith('terminal.'))).toBe(true);

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    expect(check(report, 'session_binding').status).toBe('pass');

    const fired = new Set(
      runHeuristics(buildIndex(bundle), bundle, report).map((f) => f.heuristic),
    );
    for (const id of TERMINAL_HEURISTICS) expect(fired).not.toContain(id);
  });

  it('makes a cross-submission comparison not-applicable rather than scoring it', async () => {
    // Two submissions with identical kind streams. Under 1.x that is a clone
    // signal; under a policy that removed a kind from both streams the
    // similarity is an artefact of the policy, so the pair must be skipped —
    // not scored zero, and certainly not flagged.
    const manifest = await terminalOffManifest();
    const policy = resolveCapturePolicy(manifest.policy);

    const legacyFeatures = await Promise.all(
      [0, 1].map(async () => {
        const b = await buildBundle({ sessions: [{ events: terminalHeavySession() }] });
        return extractCrossFeatures(b, buildIndex(b));
      }),
    );
    for (const f of legacyFeatures) expect(f.disabledCaptureSignals).toEqual([]);
    expect(
      editingPatternCloneHeuristic.run(legacyFeatures, DEFAULT_CROSS_HEURISTIC_CONFIG),
    ).toHaveLength(1);

    const gatedFeatures = await Promise.all(
      [0, 1].map(async () => {
        const b = await buildBundle({
          sessions: [
            {
              sessionStart: sessionStart2(manifest),
              events: applyCapturePolicy(terminalHeavySession(), policy),
            },
          ],
        });
        // The chain must be walked before the policy counts — a cross-feature
        // blob is extracted from a bundle the server re-parsed, so this mirrors
        // `loadSubmissionIndex` establishing the verdict at parse time. Without
        // it the pair would be scored, not skipped (see §6).
        expect(
          check(await runValidation(b, { rootPubkeyHex: keys.rootPubkeyHex }), 'session_binding')
            .status,
        ).toBe('pass');
        return extractCrossFeatures(b, buildIndex(b));
      }),
    );
    for (const f of gatedFeatures) expect(f.disabledCaptureSignals).toEqual(['terminal']);
    expect(editingPatternCloneHeuristic.run(gatedFeatures, DEFAULT_CROSS_HEURISTIC_CONFIG)).toEqual(
      [],
    );
  });
});

// ---------------------------------------------------------------------------
// 6. An UNVERIFIED policy is not a policy.
//
//    Section 5 proves a signed policy narrows what the analyzer expects. This
//    section proves the converse, which is the security-relevant half: a policy
//    whose chain did not verify must narrow nothing. The failure direction is
//    deliberate — when in doubt, heuristics fire and staff review. Never
//    silently fewer flags.
// ---------------------------------------------------------------------------

describe('an unverified capture policy', () => {
  const ALL_ON = { capture: { selection_change: true, focus_change: true, terminal: true } };
  const TERMINAL_OFF = { capture: { selection_change: true, focus_change: true, terminal: false } };

  /** A genuinely-signed manifest whose `policy` was edited afterwards. */
  async function tamperedPolicyManifest(): Promise<Manifest> {
    const genuine = await buildManifest2({
      keys,
      courseId: COURSE_ID,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
      policy: ALL_ON,
    });
    return { ...genuine, policy: TERMINAL_OFF };
  }

  /** A genuinely-signed manifest that really does disable terminal capture. */
  async function signedTerminalOffManifest(): Promise<Manifest> {
    return buildManifest2({
      keys,
      courseId: COURSE_ID,
      assignmentId: ASSIGNMENT_ID,
      semester: SEMESTER,
      issuedAt: ISSUED_AT,
      filesUnderReview: [FILE],
      policy: TERMINAL_OFF,
    });
  }

  /**
   * The terminal-heavy stream under `manifest`. A recorder that honoured a
   * terminal-off policy would not have written these events — which is the
   * point: the student edited the policy in *after* recording, precisely to have
   * the analyzer discount events that are already in the log.
   */
  async function bundleWith(manifest: Manifest): Promise<Bundle> {
    return buildBundle({
      sessions: [{ sessionStart: sessionStart2(manifest), events: terminalHeavySession() }],
    });
  }

  it('is ignored when the policy was edited after signing — the heuristics still fire', async () => {
    const bundle = await bundleWith(await tamperedPolicyManifest());

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    expect(check(report, 'session_binding').status).toBe('fail');

    // The edited policy must not have narrowed anything.
    const resolved = resolveBundleCapturePolicy(bundle);
    expect(resolved.disabledSignals).toEqual([]);
    expect(resolved.effective.terminal).toBe(true);
    expect(isSignalCaptured(bundle, 'terminal')).toBe(true);
    // …but the attempt is recorded, so staff can see what was reached for.
    expect(resolved.source).toBe('unverified_manifest');
    expect(resolved.claimedDisabledSignals).toEqual(['terminal']);

    const fired = new Set(
      runHeuristics(buildIndex(bundle), bundle, report).map((f) => f.heuristic),
    );
    for (const id of TERMINAL_HEURISTICS) expect(fired).toContain(id);
    expect(fired).toContain('session_binding_invalid');

    // And the summary must not present the edited policy as course-sanctioned.
    const summary = await summarizeBundleManifest(bundle, keys.rootPubkeyHex);
    expect(summary.trust_chain).toBe('invalid');
    expect(summary.disabled_signals).toEqual([]);
    expect(summary.trust_chain_detail).toContain('terminal');
  });

  it('is ignored when no root key is configured, even though the signature is genuine', async () => {
    // A deployment that never set the root key cannot verify anything, so it
    // cannot honour a policy either. This IS a behaviour change for such a
    // deployment — a course that legitimately disabled terminal capture will see
    // these heuristics fire again — and it is the correct direction: an
    // unconfigured root key is a deployment error, and the failure must be
    // visible (flags + a `skipped` check 2) rather than silent suppression.
    const bundle = await bundleWith(await signedTerminalOffManifest());

    const report = await runValidation(bundle);
    expect(check(report, 'session_binding').status).toBe('skipped');

    const resolved = resolveBundleCapturePolicy(bundle);
    expect(resolved.disabledSignals).toEqual([]);
    expect(resolved.source).toBe('unverified_manifest');
    expect(resolved.claimedDisabledSignals).toEqual(['terminal']);

    const fired = new Set(
      runHeuristics(buildIndex(bundle), bundle, report).map((f) => f.heuristic),
    );
    for (const id of TERMINAL_HEURISTICS) expect(fired).toContain(id);

    const summary = await summarizeBundleManifest(bundle);
    expect(summary.trust_chain).toBe('unconfigured');
    expect(summary.disabled_signals).toEqual([]);
    expect(summary.trust_chain_detail).toContain('terminal');
  });

  it('control: the same policy IS honoured once the chain verifies', async () => {
    const bundle = await bundleWith(await signedTerminalOffManifest());

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    expect(check(report, 'session_binding').status).toBe('pass');

    const resolved = resolveBundleCapturePolicy(bundle);
    expect(resolved.source).toBe('manifest_2_0');
    expect(resolved.disabledSignals).toEqual(['terminal']);

    const fired = new Set(
      runHeuristics(buildIndex(bundle), bundle, report).map((f) => f.heuristic),
    );
    for (const id of TERMINAL_HEURISTICS) expect(fired).not.toContain(id);
  });

  it('cannot be used to shield a collusion partner from cross-submission flags', async () => {
    // The worst consequence of an unverified policy is not the self-inflicted
    // one. `editing_pattern_clone` is not-applicable when EITHER side had a
    // kind-stream signal disabled, so a student who tampers with their own
    // manifest absorbs a `session_binding_invalid` flag and in exchange shields
    // their counterpart, against whom nothing is recorded at all.
    const honest = await bundleWith(await buildManifest2({ keys, courseId: COURSE_ID }));
    const tampered = await bundleWith(await tamperedPolicyManifest());

    for (const b of [honest, tampered]) {
      await runValidation(b, { rootPubkeyHex: keys.rootPubkeyHex });
    }

    const features = [honest, tampered].map((b) => extractCrossFeatures(b, buildIndex(b)));
    expect(features.map((f) => f.disabledCaptureSignals)).toEqual([[], []]);
    expect(editingPatternCloneHeuristic.run(features, DEFAULT_CROSS_HEURISTIC_CONFIG)).toHaveLength(
      1,
    );
  });
});

// ---------------------------------------------------------------------------
// 7. A suppressed event leaves no seq hole.
// ---------------------------------------------------------------------------

describe('policy suppression and the hash chain', () => {
  it('renumbers around suppressed events: no seq hole, checks 3 and 4 both pass', async () => {
    const manifest = await buildManifest2({
      keys,
      courseId: COURSE_ID,
      filesUnderReview: [FILE],
      policy: { capture: { selection_change: false, focus_change: false, terminal: false } },
    });
    const policy = resolveCapturePolicy(manifest.policy);

    const full = studentSession();
    const kept = applyCapturePolicy(full, policy);
    // Something must actually have been dropped, or this proves nothing.
    expect(kept.length).toBeLessThan(full.length);
    expect(kept.some((e) => e.kind.startsWith('terminal.'))).toBe(false);
    expect(kept.some((e) => e.kind === 'selection.change')).toBe(false);
    expect(kept.some((e) => e.kind === 'focus.change')).toBe(false);

    const bundle = await buildBundle({
      sessions: [{ sessionStart: sessionStart2(manifest), events: kept }],
      submissionFiles: [{ path: FILE, status: 'present', content: CODE }],
    });

    // session.start plus every surviving event, numbered 0..n-1 with no gap.
    const seqs = bundle.sessions[0]!.events.map((e) => e.seq);
    expect(seqs).toEqual(Array.from({ length: kept.length + 1 }, (_, i) => i));

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    expect(check(report, 'chain_integrity').status).toBe('pass');
    expect(check(report, 'seq_gaps').status).toBe('pass');
    expect(statuses(report)).toEqual(ALL_PASS);
  });

  it('control: a real hole in the same stream is caught by check 4', async () => {
    // Proves the assertion above can fail. Dropping an entry AFTER chaining is
    // what a deletion looks like, and it must not be confusable with a
    // policy-suppressed event.
    const manifest = await buildManifest2({
      keys,
      courseId: COURSE_ID,
      filesUnderReview: [FILE],
      policy: { capture: { selection_change: false, focus_change: false, terminal: false } },
    });
    const policy = resolveCapturePolicy(manifest.policy);
    const kept = applyCapturePolicy(studentSession(), policy);

    const bundle = await buildBundle({
      sessions: [{ sessionStart: sessionStart2(manifest), events: kept }],
      submissionFiles: [{ path: FILE, status: 'present', content: CODE }],
      tamper: { addSeqGap: { sessionIndex: 0, afterEntryIndex: 1 } },
    });

    const report = await runValidation(bundle, { rootPubkeyHex: keys.rootPubkeyHex });
    expect(check(report, 'seq_gaps').status).toBe('fail');
    // The trust chain is untouched by a deleted entry.
    expect(check(report, 'session_binding').status).toBe('pass');
  });
});
