/**
 * EnrollView — the student's enrollment page, at identity `format_version` 2.1.
 *
 * Route: `/enroll` (RequireAuth, no AppShell). The first page in this analyzer
 * a student rather than course staff can reach, and the only way a student
 * obtains a credential.
 *
 * ## There is no course or semester on this page
 *
 * It previously posted to `POST /semesters/:id/enrollment` and took the
 * semester from `?semester=<uuid>`. That route is gone from the server, and the
 * page now posts to `POST /api/v1/identity/credential`, which takes no path
 * parameter at all: a 2.1 credential names no course, no semester, and no
 * assignment. One credential serves every course forever.
 *
 * ## Coming back is normal — that is how a second machine is set up
 *
 * A student who works on a laptop and a desktop enrols BOTH here. Each machine
 * generates its own master secret and its own keypair; signing in with the same
 * account returns the same global `student_ref`; each machine gets its own
 * credential over that shared ref. Contributor resolution groups on the ref, so
 * both machines are one person and the student can swap freely.
 *
 * The page must therefore never read like a duplicate warning on a return
 * visit. `reissued` alone cannot tell "added a machine" from "asked the same
 * machine for another credential", so the copy is driven by `machine_count` and
 * `key_first_issued` instead — see {@link describeIssuance}.
 *
 * The corollary for the copy at the bottom of the page: "Back Up / Restore
 * Student Identity Secret" is a BACKUP, not the second-machine path. Telling a
 * student to hand-carry the one value that can sign as them, for a flow that
 * does not need it, is a real harm dressed up as a tip.
 *
 * So the semester input is not merely unused, it would be misleading — there is
 * nothing to scope, and a `?semester=` query param is now silently irrelevant
 * rather than wrong. Course membership is answered later, from the roster, by
 * the server, against data it owns; requiring it up front was the deadlock that
 * identity 2.1 exists to remove.
 *
 * ## The private key is not here, and cannot be
 *
 * The student's master secret and private key are generated by, and never
 * leave, their recorder (`identity/secret-store.ts`). This page handles a PUBLIC
 * key on the way in and a signed credential on the way out; there is no code
 * path here that generates, derives, receives or transmits private key
 * material, and there must never be one. §5a: "there is no server-side key
 * store to breach" — a browser form that touched a private key would quietly
 * undo that.
 *
 * The uncomfortable corollary: a student master secret is ALSO 64 lowercase hex
 * characters, so the VALUE cannot be told from a public key by inspection, here
 * or on the server. Two defences, both partial and both necessary:
 * `normalizeStudentPubkey` refuses a paste carrying the recorder's
 * secret-export marker or its prose, and the warning beside the input covers
 * the student who strips the marker by hand.
 *
 * ## Both hops are checked before the student leaves
 *
 * A key that is one character short, and a credential that lost its last brace,
 * are the same class of failure: text moved by hand between two apps. Step 1
 * validates the key locally before spending a request on it; step 2 offers to
 * re-check what the student actually pasted, using the exact log-core parsers
 * the recorder uses (see `enrollment-token.ts`). Neither is decoration — a
 * mangled paste that fails silently costs a student their attribution and is
 * discovered, if ever, during an integrity investigation.
 */

import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ApiError, UnauthorizedError } from '../../api/client.js';
import { useMe, useMintCredential } from '../../api/queries.js';
import { ErrorRegion } from '../../components/a11y/ErrorRegion.js';
import { StatusRegion } from '../../components/a11y/StatusRegion.js';
import { ProvenanceMark } from '../../components/nav/ProvenanceMark.js';
import {
  buildRecorderPasteText,
  checkRecorderPasteText,
  normalizeStudentPubkey,
} from './enrollment-token.js';
import type { StudentCredentialResponse } from '@provenance/shared/api-schemas';

// ---------------------------------------------------------------------------
// Success presentation
// ---------------------------------------------------------------------------

/**
 * What the green panel says, chosen by what actually happened to this student's
 * machines rather than by the bare `reissued` flag.
 *
 * `reissued` is true whenever the account has enrolled before, which is exactly
 * what a student legitimately doing the supported thing — setting up a second
 * machine — will see. Presenting that as "you have already enrolled" alarms
 * them about the one flow we want to be routine. So the page speaks in machines
 * instead, using the two fields that can tell the cases apart:
 *
 *  - `key_first_issued` — this key had never been issued before, i.e. a machine
 *    being set up for the first time;
 *  - `machine_count` — how many distinct keys this student has enrolled, which
 *    is one per machine because each machine derives its own.
 *
 * The count can under-report on an account that enrolled before the server
 * started keeping a history, and over-report for a student who lost their
 * secret and re-derived on the SAME machine. Both are harmless here: the number
 * is context in a reassuring sentence, not a claim anyone acts on.
 */
export function describeIssuance(response: StudentCredentialResponse): string {
  if (!response.key_first_issued) {
    return (
      'This machine was already set up, so this is simply a fresh credential for it. The one ' +
      'you had before still works until it expires — nothing you have already recorded is ' +
      'affected.'
    );
  }
  if (response.machine_count > 1) {
    return (
      `That is ${response.machine_count} machines set up on this account. Each machine has its ` +
      'own credential and your other ones keep working — all of them are you, under the same ' +
      'ref, so your work is never split between two people.'
    );
  }
  return (
    'Copy it into VS Code with "Provenance: Import Enrollment Token". This credential works ' +
    'for every course. Setting up another machine later? Just come back here and do this ' +
    'again — that is the normal way to add one.'
  );
}

// ---------------------------------------------------------------------------
// Failure presentation
// ---------------------------------------------------------------------------

export interface MintFailure {
  /** One line naming what went wrong, in the student's terms. */
  readonly title: string;
  /** What to do about it. Always actionable — never "contact support". */
  readonly detail: string;
}

/**
 * Turn an issue failure into something a student can act on.
 *
 * Every branch here corresponds to a real, reachable response from
 * `POST /api/v1/identity/credential` (see
 * `packages/server/src/api/v1/routes/credential.ts` and `errors.ts`). The
 * catch-all at the end covers the case with no server response at all — the
 * campus wifi dropping mid-request — which `apiFetch` surfaces as a raw
 * `TypeError` from `fetch`, not as an `ApiError`.
 *
 * There is deliberately NO roster branch, and there must not be one: a roster
 * precondition is exactly the deadlock identity 2.1 removes, and the route has
 * no roster check to fail. `NOT_FOUND` is gone for the same structural reason —
 * the path carries no semester id, so there is nothing to 404.
 *
 * Deliberately does NOT echo `err.message` for the mapped codes. The server's
 * wording is written for an API consumer; a student needs to know which of the
 * plausible causes applies to them and what to do next.
 */
export function describeMintError(err: unknown): MintFailure {
  if (err instanceof UnauthorizedError) {
    return {
      title: 'Your session expired',
      detail: 'Sign in again, then come back to this page and re-paste your key.',
    };
  }

  if (err instanceof ApiError) {
    switch (err.code) {
      case 'CREDENTIAL_UNAVAILABLE':
        return {
          title: 'Your institution is not ready to issue credentials yet',
          detail:
            'The signing key for your institution is not configured, or its certificate has ' +
            'lapsed. This is not something you can fix — tell your course staff, and keep ' +
            'working in the meantime. Your recorder still records without a credential; you ' +
            'can import one later.',
        };
      case 'CREDENTIAL_SESSION_REQUIRED':
        return {
          title: 'This needs an interactive login',
          detail:
            'This page must be used with a normal Google sign-in. An API token cannot issue a ' +
            'credential, because the credential is the claim that the work is yours.',
        };
      case 'VIEW_AS_READ_ONLY':
        return {
          title: 'Credentials cannot be issued while viewing as another user',
          detail:
            'Exit view-as and sign in as yourself. A credential issued under an impersonated ' +
            'account would attribute work to someone by an operator’s action, which is exactly ' +
            'what this chain exists to make impossible.',
        };
      case 'VALIDATION':
        return {
          title: 'The server rejected that key',
          detail:
            'Copy the key again with "Provenance: Show My Enrollment Key" and paste it without ' +
            'editing it.',
        };
      case 'RATE_LIMITED':
        return {
          title: 'Too many attempts',
          detail: 'Wait a minute and try again.',
        };
      default:
        return {
          title: 'The server could not issue a credential',
          detail: `${err.message} If this keeps happening, tell your course staff.`,
        };
    }
  }

  return {
    title: 'Could not reach the server',
    detail:
      'Check your connection and try again. Nothing was issued, so it is safe to press the ' +
      'button again.',
  };
}

// ---------------------------------------------------------------------------
// Step 2 — the issued credential
// ---------------------------------------------------------------------------

/**
 * Show the token, and make the paste hard to get wrong.
 *
 * The affordances are ordered by how much they help: a Copy button first (the
 * only path with no chance of a partial selection), then the exact words the
 * recorder will say on success (so a student can confirm the round trip
 * themselves), then an optional box that re-checks what they actually pasted.
 */
function TokenPanel({
  response,
  onReset,
}: {
  response: StudentCredentialResponse;
  onReset: () => void;
}) {
  const pasteText = buildRecorderPasteText(response);
  const [copied, setCopied] = useState(false);
  const [verifyText, setVerifyText] = useState('');

  function handleCopy() {
    // Optional-chained: jsdom and any non-secure context have no clipboard. The
    // textarea below is the fallback, and it selects on focus.
    void navigator.clipboard
      ?.writeText(pasteText)
      .then(() => {
        setCopied(true);
        window.setTimeout(() => setCopied(false), 2000);
      })
      .catch(() => {
        /* fall back to manual selection */
      });
  }

  const verdict = verifyText.trim().length === 0 ? null : checkRecorderPasteText(verifyText);
  const isSameToken =
    verdict !== null &&
    verdict.ok &&
    verdict.institutionId === response.credential.institution_id &&
    verdict.studentRef === response.credential.student_ref &&
    verdict.studentPubkey === response.credential.student_pubkey;

  return (
    <section className="mt-8" data-testid="enroll-token-panel">
      <div className="rounded-lg border border-green-300 bg-green-50 p-4">
        <h2 className="text-sm font-semibold text-green-900" data-testid="enroll-success-heading">
          {response.key_first_issued && response.machine_count > 1
            ? `This machine is set up for ${response.institution_id}`
            : `Your credential for ${response.institution_id} is ready`}
        </h2>
        <p className="mt-1 text-xs text-green-900" data-testid="enroll-issuance-note">
          {describeIssuance(response)}
        </p>
      </div>

      <div className="mt-4 rounded-lg border border-gray-200 bg-white p-4">
        <label htmlFor="enroll-token-text" className="block text-sm font-semibold text-gray-900">
          Step 2 — paste this into VS Code
        </label>
        <p className="mt-1 text-xs text-gray-600">
          Run <span className="font-mono">Provenance: Import Enrollment Token</span> from the
          command palette and paste the whole line. It is one line on purpose — the recorder prompts
          with a single-line box.
        </p>

        <div className="mt-3 flex items-stretch gap-2">
          <textarea
            id="enroll-token-text"
            readOnly
            rows={4}
            value={pasteText}
            onFocus={(e) => e.currentTarget.select()}
            data-testid="enroll-token-value"
            className="flex-1 resize-none rounded border border-gray-300 bg-gray-50 px-2 py-1.5 font-mono text-xs break-all text-gray-900"
          />
          <button
            type="button"
            onClick={handleCopy}
            data-testid="enroll-token-copy"
            className="shrink-0 self-start rounded bg-orange-700 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-orange-800 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2"
          >
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>

        <p className="mt-2 text-xs text-gray-500" data-testid="enroll-token-length">
          {pasteText.length} characters. If what you pasted is shorter, it got cut off.
        </p>

        <div className="mt-4 rounded border border-gray-200 bg-gray-50 p-3">
          <p className="text-xs font-semibold text-gray-700">How you will know it worked</p>
          <p className="mt-1 text-xs text-gray-600">
            VS Code shows{' '}
            <span className="font-mono" data-testid="enroll-expected-message">
              Provenance: enrolled at {response.institution_id}
            </span>
            . If it says the credential was not accepted, nothing was saved — copy it again from
            here.
          </p>
          <p className="mt-2 text-xs text-gray-600" data-testid="enroll-version-note">
            If VS Code instead says the paste is{' '}
            <span className="font-mono">unsupported_format_version</span>, your Provenance extension
            is too old to read this credential. Nothing was saved and nothing is broken — update the
            extension and paste it again.
          </p>
        </div>

        <details className="mt-4">
          <summary className="cursor-pointer text-xs font-medium text-gray-700">
            Check what you pasted
          </summary>
          <p className="mt-2 text-xs text-gray-600">
            Paste it back here and this page will run the same checks the recorder runs. Nothing is
            sent anywhere.
          </p>
          <textarea
            rows={3}
            value={verifyText}
            onChange={(e) => setVerifyText(e.target.value)}
            aria-label="Paste the token back to check it"
            data-testid="enroll-verify-input"
            className="mt-2 w-full resize-none rounded border border-gray-300 px-2 py-1.5 font-mono text-xs break-all"
          />
          {verdict !== null &&
            (verdict.ok ? (
              isSameToken ? (
                <StatusRegion className="mt-2 text-xs font-medium text-green-700">
                  <span data-testid="enroll-verify-ok">
                    That is exactly the token above. The recorder will accept it.
                  </span>
                </StatusRegion>
              ) : (
                <ErrorRegion className="mt-2 text-xs font-medium text-amber-700">
                  <span data-testid="enroll-verify-other">
                    That is a valid credential, but not the one on this page — it is for{' '}
                    {verdict.institutionId}. Make sure you paste the credential shown above.
                  </span>
                </ErrorRegion>
              )
            ) : (
              <ErrorRegion className="mt-2 text-xs font-medium text-red-600">
                <span data-testid="enroll-verify-error">{verdict.message}</span>
              </ErrorRegion>
            ))}
        </details>
      </div>

      <div className="mt-4 rounded-lg border border-gray-200 bg-white p-4">
        <h3 className="text-sm font-semibold text-gray-900">What was issued</h3>
        <dl className="mt-2 space-y-1 text-xs text-gray-600">
          <div className="flex gap-2">
            <dt className="w-28 shrink-0 text-gray-500">Institution</dt>
            <dd className="font-mono break-all">{response.institution_id}</dd>
          </div>
          <div className="flex gap-2">
            <dt className="w-28 shrink-0 text-gray-500">Your ref</dt>
            <dd className="font-mono break-all" data-testid="enroll-student-ref">
              {response.student_ref}
            </dd>
          </div>
          <div className="flex gap-2">
            <dt className="w-28 shrink-0 text-gray-500">Valid until</dt>
            <dd className="font-mono break-all">{response.credential.expires_at}</dd>
          </div>
          {response.machine_count > 1 && (
            <div className="flex gap-2">
              <dt className="w-28 shrink-0 text-gray-500">Machines</dt>
              <dd data-testid="enroll-machine-count">
                {response.machine_count} set up on this account
              </dd>
            </div>
          )}
        </dl>
        <p className="mt-2 text-xs text-gray-500">
          Your ref is an opaque id, not your student number. It is what a shared repository shows
          about you — a partner reading your log sees this, not your name. It is the same in every
          course, and it names no course itself.
        </p>
      </div>

      <button
        type="button"
        onClick={onReset}
        data-testid="enroll-reset"
        className="mt-4 text-xs font-medium text-orange-700 underline-offset-4 hover:underline"
      >
        Enroll a different key
      </button>
    </section>
  );
}

// ---------------------------------------------------------------------------
// EnrollView
// ---------------------------------------------------------------------------

export function EnrollView() {
  const { data: me } = useMe();

  const [pubkeyText, setPubkeyText] = useState('');
  // Only shown after a submit attempt: flagging "paste your key first" while the
  // student is still walking back from VS Code is noise, not help.
  const [showKeyError, setShowKeyError] = useState(false);

  const mint = useMintCredential();
  const pubkey = normalizeStudentPubkey(pubkeyText);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setShowKeyError(true);
    if (!pubkey.ok) return;
    mint.mutate(pubkey.pubkey);
  }

  function handleReset() {
    mint.reset();
    setPubkeyText('');
    setShowKeyError(false);
  }

  const failure = mint.isError ? describeMintError(mint.error) : null;

  return (
    <main className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-2xl px-6 py-12">
        <header>
          <ProvenanceMark className="h-12 w-12" />
          <h1 className="mt-3 text-3xl font-semibold tracking-tight text-gray-900">
            Get your enrollment credential
          </h1>
          <p className="mt-3 text-sm text-gray-700">
            Your credential is what lets your courses tell that the work in your recordings is
            yours. It is not tied to a course or a semester, so one is enough for everything you
            take. Do this once per machine you work on — a laptop and a desktop each get their own,
            and both count as you.
          </p>
          {me !== undefined && (
            <p className="mt-3 text-xs text-gray-600" data-testid="enroll-signed-in-as">
              Signed in as <span className="font-medium text-gray-900">{me.user.email}</span>. The
              credential is issued to this account, so make sure it is your university account.{' '}
              <Link to="/login" className="text-orange-700 underline-offset-4 hover:underline">
                Not you?
              </Link>
            </p>
          )}
        </header>

        {mint.data !== undefined ? (
          <TokenPanel response={mint.data} onReset={handleReset} />
        ) : (
          <form onSubmit={handleSubmit} className="mt-8" data-testid="enroll-form">
            {/* ── Step 1 — the public key ─────────────────────────────── */}
            <div className="rounded-lg border border-gray-200 bg-white p-4">
              <label htmlFor="enroll-pubkey" className="block text-sm font-semibold text-gray-900">
                Step 1 — paste your enrollment key
              </label>
              <p className="mt-1 text-xs text-gray-600">
                In VS Code, open the command palette and run{' '}
                <span className="font-mono">Provenance: Show My Enrollment Key</span>. It copies the
                key to your clipboard.
              </p>

              <div className="mt-3 rounded border border-amber-300 bg-amber-50 p-3">
                <p className="text-xs font-semibold text-amber-900">
                  Paste the enrollment KEY, not your identity secret.
                </p>
                <p className="mt-1 text-xs text-amber-900">
                  Your identity secret — the one from{' '}
                  <span className="font-mono">Back Up Student Identity Secret</span>, which warns
                  you to keep it private — is also 64 characters. This page refuses it if you paste
                  it with the label the recorder puts on it, but the bare value is indistinguishable
                  from your key and nothing here can catch that. Anyone holding that secret can sign
                  work as you, in every course. It should never be typed into a website, including
                  this one.
                </p>
              </div>

              <input
                id="enroll-pubkey"
                type="text"
                autoComplete="off"
                spellCheck={false}
                value={pubkeyText}
                onChange={(e) => {
                  setPubkeyText(e.target.value);
                  setShowKeyError(false);
                }}
                placeholder="64 characters, digits and a–f"
                data-testid="enroll-pubkey-input"
                aria-invalid={showKeyError && !pubkey.ok}
                aria-describedby={showKeyError && !pubkey.ok ? 'enroll-pubkey-error' : undefined}
                className="mt-3 w-full rounded border border-gray-300 px-3 py-1.5 font-mono text-sm break-all focus:outline-none focus:ring-2 focus:ring-orange-500"
              />
              {pubkey.ok && (
                <StatusRegion className="mt-1.5 text-xs text-green-700">
                  <span data-testid="enroll-pubkey-ok">That looks like a valid key.</span>
                </StatusRegion>
              )}
              {showKeyError && !pubkey.ok && (
                <ErrorRegion className="mt-1.5 text-xs text-red-600">
                  <span id="enroll-pubkey-error" data-testid="enroll-pubkey-error">
                    {pubkey.reason}
                  </span>
                </ErrorRegion>
              )}
            </div>

            {failure !== null && (
              <ErrorRegion className="mt-4 rounded-lg border border-red-300 bg-red-50 p-4">
                <p className="text-sm font-semibold text-red-900" data-testid="enroll-error-title">
                  {failure.title}
                </p>
                <p className="mt-1 text-xs text-red-900" data-testid="enroll-error-detail">
                  {failure.detail}
                </p>
                {mint.error instanceof UnauthorizedError && (
                  <Link
                    to="/login?next=%2Fenroll"
                    className="mt-2 inline-block text-xs font-medium text-red-900 underline"
                    data-testid="enroll-error-signin"
                  >
                    Sign in again
                  </Link>
                )}
              </ErrorRegion>
            )}

            <button
              type="submit"
              disabled={mint.isPending}
              data-testid="enroll-submit"
              className="mt-6 inline-flex w-full items-center justify-center rounded-md bg-orange-700 px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-orange-800 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2 disabled:opacity-50"
            >
              {mint.isPending ? 'Issuing…' : 'Get my credential'}
            </button>
            {mint.isPending && (
              <StatusRegion className="mt-2 text-center text-xs text-gray-500">
                Issuing your credential…
              </StatusRegion>
            )}
          </form>
        )}

        <section className="mt-12 border-t border-gray-200 pt-6">
          <h2 className="text-sm font-semibold text-gray-900">Why it works this way</h2>
          <p className="mt-2 text-xs text-gray-600">
            Your recorder generates a key pair on your machine. The private half never leaves it —
            not to this page, not to the server, and there is no copy anywhere for anyone to lose or
            hand over. What you paste above is the public half; all the server does is sign a
            statement that this public key belongs to you. That signed statement is the credential.
          </p>
          <p className="mt-2 text-xs text-gray-600">
            The credential says who you are, not which classes you are in. It names no course and no
            semester, so you never have to come back here when you start a new one — and you do not
            have to be on a roster yet to get it, which matters because rosters usually arrive after
            your first submission.
          </p>
          <p className="mt-2 text-xs text-gray-600" data-testid="enroll-second-machine-note">
            To work on a second machine, install the recorder there and come back to this page with
            that machine&rsquo;s key. It gets its own credential, and both machines are recognised
            as you — you can swap between them freely, and you never have to move your identity
            secret between them to do it.
          </p>
          <p className="mt-2 text-xs text-gray-600">
            The recorder&rsquo;s <span className="font-mono">Back Up Student Identity Secret</span>{' '}
            command is for exactly that — a backup, kept in your password manager. There is no copy
            on any server, so it is the only way to recover a machine&rsquo;s identity if you lose
            it. You do not need it to add a machine.
          </p>
        </section>
      </div>
    </main>
  );
}
