/**
 * EnrollView — the student's enrollment page (program spec §5a — S2).
 *
 * Route: `/enroll` (RequireAuth, no AppShell). The first page in this analyzer
 * a student rather than course staff can reach, and the only way a student
 * obtains an enrollment token.
 *
 * ## The private key is not here, and cannot be
 *
 * The student's master secret and per-course private key are generated by, and
 * never leave, their recorder (`identity/secret-store.ts`). This page handles a
 * PUBLIC key on the way in and a signed token on the way out; there is no code
 * path here that generates, derives, receives or transmits private key
 * material, and there must never be one. §5a: "there is no server-side key
 * store to breach" — a browser form that touched a private key would quietly
 * undo that.
 *
 * The uncomfortable corollary, called out on the page itself: a student master
 * secret is ALSO 64 lowercase hex characters, so neither this page nor the
 * server can tell one from a public key by inspection. The defence is the
 * warning next to the input, which is why it is worded as strongly as it is.
 *
 * ## Where the semester id comes from
 *
 * From the URL: `/enroll?semester=<uuid>`, the link course staff publish. There
 * is deliberately no picker, because there is deliberately no endpoint behind
 * one — a student has no `memberships` row, so every listing route on the
 * server 403s them by design, and `GET /me` returns `memberships: []`. When the
 * link is missing or malformed the page falls back to asking for the id, rather
 * than dead-ending a student whose course pasted the URL into Piazza badly.
 *
 * ## Both hops are checked before the student leaves
 *
 * A key that is one character short, and a token that lost its last brace, are
 * the same class of failure: text moved by hand between two apps. Step 1
 * validates the key locally before spending a request on it; step 3 offers to
 * re-check the token the student actually pasted, using the exact log-core
 * parsers the recorder uses (see `enrollment-token.ts`). Neither is decoration
 * — a mangled paste that fails silently costs a student their attribution for
 * the semester and is discovered, if ever, during an integrity investigation.
 */

import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ApiError, UnauthorizedError } from '../../api/client.js';
import { useMe, useMintEnrollment } from '../../api/queries.js';
import { ErrorRegion } from '../../components/a11y/ErrorRegion.js';
import { StatusRegion } from '../../components/a11y/StatusRegion.js';
import { ProvenanceMark } from '../../components/nav/ProvenanceMark.js';
import {
  buildRecorderPasteText,
  checkRecorderPasteText,
  isSemesterId,
  normalizeStudentPubkey,
} from './enrollment-token.js';
import type { EnrollmentResponse } from '@provenance/shared/api-schemas';

// ---------------------------------------------------------------------------
// Failure presentation
// ---------------------------------------------------------------------------

export interface MintFailure {
  /** One line naming what went wrong, in the student's terms. */
  readonly title: string;
  /** What to do about it. Always actionable — never "contact support". */
  readonly detail: string;
}

/**
 * Turn a mint failure into something a student can act on.
 *
 * Every branch here corresponds to a real, reachable server response (see
 * `packages/server/src/api/v1/routes/enrollment.ts` and `errors.ts`). The
 * catch-all at the end covers the case with no server response at all — the
 * campus wifi dropping mid-request — which `apiFetch` surfaces as a raw
 * `TypeError` from `fetch`, not as an `ApiError`.
 *
 * Deliberately does NOT echo `err.message` for the mapped codes. The server's
 * wording is written for an API consumer ("This account does not match a
 * student on the roster for this semester"); a student needs to know which of
 * the two or three plausible causes applies to them and what to do next.
 */
export function describeMintError(err: unknown): MintFailure {
  if (err instanceof UnauthorizedError) {
    return {
      title: 'Your session expired',
      detail: 'Sign in again, then come back to this page and re-paste your key.',
    };
  }

  if (err instanceof ApiError) {
    switch (err.code) {
      case 'ENROLLMENT_NOT_ON_ROSTER':
        return {
          title: 'You are not on the roster for this semester',
          detail:
            'Check that you are signed in with your university account (shown above) and that ' +
            'this is the right course link. If you enrolled or changed sections recently, your ' +
            'course may not have uploaded the new roster yet — ask your course staff to add you, ' +
            'then try again.',
        };
      case 'ENROLLMENT_ROSTER_AMBIGUOUS':
        return {
          title: 'Your course roster lists this email twice',
          detail:
            'The server will not guess which entry is you, because guessing wrong would ' +
            'attribute your work to another student. Ask your course staff to remove the ' +
            'duplicate roster entry, then try again.',
        };
      case 'ENROLLMENT_UNAVAILABLE':
        return {
          title: 'This course is not ready to issue tokens yet',
          detail:
            'Enrollment is set up by course staff once per semester, and it is not finished ' +
            'here. This is not something you can fix — tell your course staff, and keep ' +
            'working in the meantime. Your recorder still records without a token; you can ' +
            'import one later.',
        };
      case 'ENROLLMENT_SESSION_REQUIRED':
        return {
          title: 'Enrollment needs an interactive login',
          detail:
            'This page must be used with a normal Google sign-in. An API token cannot mint an ' +
            'enrollment token, because the token is the claim that the work is yours.',
        };
      case 'NOT_FOUND':
        return {
          title: 'That enrollment link does not point at a real semester',
          detail:
            'The semester in the link does not exist. Ask your course staff for the current ' +
            'enrollment link — last term’s link will not work.',
        };
      case 'VALIDATION':
        return {
          title: 'The server rejected that key',
          detail:
            'Copy the key again with "Provenance: Show My Enrollment Key" and paste it without ' +
            'editing it.',
        };
      case 'RATE_LIMITED':
        return {
          title: 'Too many attempts',
          detail: 'Wait a minute and try again.',
        };
      default:
        return {
          title: 'The server could not issue a token',
          detail: `${err.message} If this keeps happening, tell your course staff.`,
        };
    }
  }

  return {
    title: 'Could not reach the server',
    detail:
      'Check your connection and try again. Nothing was issued, so it is safe to press the ' +
      'button again.',
  };
}

// ---------------------------------------------------------------------------
// Step 3 — the minted token
// ---------------------------------------------------------------------------

/**
 * Show the token, and make the paste hard to get wrong.
 *
 * The affordances are ordered by how much they help: a Copy button first (the
 * only path with no chance of a partial selection), then the exact words the
 * recorder will say on success (so a student can confirm the round trip
 * themselves), then an optional box that re-checks what they actually pasted.
 */
function TokenPanel({ response, onReset }: { response: EnrollmentResponse; onReset: () => void }) {
  const pasteText = buildRecorderPasteText(response);
  const [copied, setCopied] = useState(false);
  const [verifyText, setVerifyText] = useState('');

  function handleCopy() {
    // Optional-chained: jsdom and any non-secure context have no clipboard. The
    // textarea below is the fallback, and it selects on focus.
    void navigator.clipboard
      ?.writeText(pasteText)
      .then(() => {
        setCopied(true);
        window.setTimeout(() => setCopied(false), 2000);
      })
      .catch(() => {
        /* fall back to manual selection */
      });
  }

  const verdict = verifyText.trim().length === 0 ? null : checkRecorderPasteText(verifyText);
  const isSameToken =
    verdict !== null &&
    verdict.ok &&
    verdict.courseId === response.enrollment.course_id &&
    verdict.studentRef === response.enrollment.student_ref &&
    verdict.studentPubkey === response.enrollment.student_pubkey;

  return (
    <section className="mt-8" data-testid="enroll-token-panel">
      <div className="rounded-lg border border-green-300 bg-green-50 p-4">
        <h2 className="text-sm font-semibold text-green-900" data-testid="enroll-success-heading">
          Your enrollment token for {response.course_id} is ready
        </h2>
        <p className="mt-1 text-xs text-green-900">
          {response.reissued
            ? 'This key was already enrolled, so the token was re-issued. That is expected if ' +
              'you are setting up a second machine — nothing you did earlier stopped working.'
            : 'Copy it into VS Code with "Provenance: Import Enrollment Token".'}
        </p>
      </div>

      <div className="mt-4 rounded-lg border border-gray-200 bg-white p-4">
        <label htmlFor="enroll-token-text" className="block text-sm font-semibold text-gray-900">
          Step 3 — paste this into VS Code
        </label>
        <p className="mt-1 text-xs text-gray-600">
          Run <span className="font-mono">Provenance: Import Enrollment Token</span> from the
          command palette and paste the whole line. It is one line on purpose — the recorder prompts
          with a single-line box.
        </p>

        <div className="mt-3 flex items-stretch gap-2">
          <textarea
            id="enroll-token-text"
            readOnly
            rows={4}
            value={pasteText}
            onFocus={(e) => e.currentTarget.select()}
            data-testid="enroll-token-value"
            className="flex-1 resize-none rounded border border-gray-300 bg-gray-50 px-2 py-1.5 font-mono text-xs break-all text-gray-900"
          />
          <button
            type="button"
            onClick={handleCopy}
            data-testid="enroll-token-copy"
            className="shrink-0 self-start rounded bg-orange-700 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-orange-800 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2"
          >
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>

        <p className="mt-2 text-xs text-gray-500" data-testid="enroll-token-length">
          {pasteText.length} characters. If what you pasted is shorter, it got cut off.
        </p>

        <div className="mt-4 rounded border border-gray-200 bg-gray-50 p-3">
          <p className="text-xs font-semibold text-gray-700">How you will know it worked</p>
          <p className="mt-1 text-xs text-gray-600">
            VS Code shows{' '}
            <span className="font-mono" data-testid="enroll-expected-message">
              Provenance: enrolled in {response.course_id}
            </span>
            . If it says the token was not accepted, nothing was saved — copy it again from here.
          </p>
        </div>

        <details className="mt-4">
          <summary className="cursor-pointer text-xs font-medium text-gray-700">
            Check what you pasted
          </summary>
          <p className="mt-2 text-xs text-gray-600">
            Paste it back here and this page will run the same checks the recorder runs. Nothing is
            sent anywhere.
          </p>
          <textarea
            rows={3}
            value={verifyText}
            onChange={(e) => setVerifyText(e.target.value)}
            aria-label="Paste the token back to check it"
            data-testid="enroll-verify-input"
            className="mt-2 w-full resize-none rounded border border-gray-300 px-2 py-1.5 font-mono text-xs break-all"
          />
          {verdict !== null &&
            (verdict.ok ? (
              isSameToken ? (
                <StatusRegion className="mt-2 text-xs font-medium text-green-700">
                  <span data-testid="enroll-verify-ok">
                    That is exactly the token above. The recorder will accept it.
                  </span>
                </StatusRegion>
              ) : (
                <ErrorRegion className="mt-2 text-xs font-medium text-amber-700">
                  <span data-testid="enroll-verify-other">
                    That is a valid enrollment token, but not the one on this page — it is for{' '}
                    {verdict.courseId}. Make sure you paste the right course’s token.
                  </span>
                </ErrorRegion>
              )
            ) : (
              <ErrorRegion className="mt-2 text-xs font-medium text-red-600">
                <span data-testid="enroll-verify-error">{verdict.message}</span>
              </ErrorRegion>
            ))}
        </details>
      </div>

      <div className="mt-4 rounded-lg border border-gray-200 bg-white p-4">
        <h3 className="text-sm font-semibold text-gray-900">What was issued</h3>
        <dl className="mt-2 space-y-1 text-xs text-gray-600">
          <div className="flex gap-2">
            <dt className="w-28 shrink-0 text-gray-500">Course</dt>
            <dd className="font-mono break-all">{response.course_id}</dd>
          </div>
          <div className="flex gap-2">
            <dt className="w-28 shrink-0 text-gray-500">Your ref</dt>
            <dd className="font-mono break-all" data-testid="enroll-student-ref">
              {response.student_ref}
            </dd>
          </div>
          <div className="flex gap-2">
            <dt className="w-28 shrink-0 text-gray-500">Valid until</dt>
            <dd className="font-mono break-all">{response.enrollment.expires_at}</dd>
          </div>
        </dl>
        <p className="mt-2 text-xs text-gray-500">
          Your ref is an opaque id, not your student number. It is what a shared repository shows
          about you — a partner reading your log sees this, not your name.
        </p>
      </div>

      <button
        type="button"
        onClick={onReset}
        data-testid="enroll-reset"
        className="mt-4 text-xs font-medium text-orange-700 underline-offset-4 hover:underline"
      >
        Enroll a different key or course
      </button>
    </section>
  );
}

// ---------------------------------------------------------------------------
// EnrollView
// ---------------------------------------------------------------------------

export function EnrollView() {
  const { data: me } = useMe();
  const [searchParams] = useSearchParams();

  const linkedSemester = searchParams.get('semester') ?? '';
  const semesterFromLink = isSemesterId(linkedSemester);

  const [typedSemester, setTypedSemester] = useState('');
  const semesterId = (semesterFromLink ? linkedSemester : typedSemester).trim();

  const [pubkeyText, setPubkeyText] = useState('');
  // Only shown after a submit attempt: flagging "paste your key first" while the
  // student is still walking back from VS Code is noise, not help.
  const [showKeyError, setShowKeyError] = useState(false);

  const mint = useMintEnrollment(semesterId);
  const pubkey = normalizeStudentPubkey(pubkeyText);
  const semesterOk = isSemesterId(semesterId);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setShowKeyError(true);
    if (!pubkey.ok || !semesterOk) return;
    mint.mutate(pubkey.pubkey);
  }

  function handleReset() {
    mint.reset();
    setPubkeyText('');
    setShowKeyError(false);
  }

  const failure = mint.isError ? describeMintError(mint.error) : null;

  return (
    <main className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-2xl px-6 py-12">
        <header>
          <ProvenanceMark className="h-12 w-12" />
          <h1 className="mt-3 text-3xl font-semibold tracking-tight text-gray-900">
            Get your enrollment token
          </h1>
          <p className="mt-3 text-sm text-gray-700">
            An enrollment token is what lets your course tell that the work in your recordings is
            yours. You only need one per course, per semester.
          </p>
          {me !== undefined && (
            <p className="mt-3 text-xs text-gray-600" data-testid="enroll-signed-in-as">
              Signed in as <span className="font-medium text-gray-900">{me.user.email}</span>. The
              token is issued to this account, so it must be the one on your course roster.{' '}
              <Link to="/login" className="text-orange-700 underline-offset-4 hover:underline">
                Not you?
              </Link>
            </p>
          )}
        </header>

        {mint.data !== undefined ? (
          <TokenPanel response={mint.data} onReset={handleReset} />
        ) : (
          <form onSubmit={handleSubmit} className="mt-8" data-testid="enroll-form">
            {/* ── Step 1 — the public key ─────────────────────────────── */}
            <div className="rounded-lg border border-gray-200 bg-white p-4">
              <label htmlFor="enroll-pubkey" className="block text-sm font-semibold text-gray-900">
                Step 1 — paste your enrollment key
              </label>
              <p className="mt-1 text-xs text-gray-600">
                In VS Code, open the command palette and run{' '}
                <span className="font-mono">Provenance: Show My Enrollment Key</span>. It copies the
                key to your clipboard.
              </p>

              <div className="mt-3 rounded border border-amber-300 bg-amber-50 p-3">
                <p className="text-xs font-semibold text-amber-900">
                  Paste the enrollment KEY, not your identity secret.
                </p>
                <p className="mt-1 text-xs text-amber-900">
                  Your identity secret — the one from{' '}
                  <span className="font-mono">Export Student Identity Secret</span>, which warns you
                  to keep it private — is also 64 characters, and this page cannot tell the two
                  apart. Anyone holding that secret can sign work as you, in every course. It should
                  never be typed into a website, including this one.
                </p>
              </div>

              <input
                id="enroll-pubkey"
                type="text"
                autoComplete="off"
                spellCheck={false}
                value={pubkeyText}
                onChange={(e) => {
                  setPubkeyText(e.target.value);
                  setShowKeyError(false);
                }}
                placeholder="64 characters, digits and a–f"
                data-testid="enroll-pubkey-input"
                aria-invalid={showKeyError && !pubkey.ok}
                aria-describedby={showKeyError && !pubkey.ok ? 'enroll-pubkey-error' : undefined}
                className="mt-3 w-full rounded border border-gray-300 px-3 py-1.5 font-mono text-sm break-all focus:outline-none focus:ring-2 focus:ring-orange-500"
              />
              {pubkey.ok && (
                <StatusRegion className="mt-1.5 text-xs text-green-700">
                  <span data-testid="enroll-pubkey-ok">That looks like a valid key.</span>
                </StatusRegion>
              )}
              {showKeyError && !pubkey.ok && (
                <ErrorRegion className="mt-1.5 text-xs text-red-600">
                  <span id="enroll-pubkey-error" data-testid="enroll-pubkey-error">
                    {pubkey.reason}
                  </span>
                </ErrorRegion>
              )}
            </div>

            {/* ── Step 2 — which semester ─────────────────────────────── */}
            <div className="mt-4 rounded-lg border border-gray-200 bg-white p-4">
              <h2 className="text-sm font-semibold text-gray-900">Step 2 — which course</h2>
              {semesterFromLink ? (
                <p className="mt-1 text-xs text-gray-600" data-testid="enroll-semester-from-link">
                  Using the semester from your course’s enrollment link.
                </p>
              ) : (
                <>
                  <label htmlFor="enroll-semester" className="mt-1 block text-xs text-gray-600">
                    Your course publishes an enrollment link that fills this in. If you do not have
                    one, paste the semester id your course gave you.
                  </label>
                  <input
                    id="enroll-semester"
                    type="text"
                    autoComplete="off"
                    spellCheck={false}
                    value={typedSemester}
                    onChange={(e) => setTypedSemester(e.target.value)}
                    placeholder="00000000-0000-0000-0000-000000000000"
                    data-testid="enroll-semester-input"
                    className="mt-2 w-full rounded border border-gray-300 px-3 py-1.5 font-mono text-sm focus:outline-none focus:ring-2 focus:ring-orange-500"
                  />
                  {typedSemester.trim().length > 0 && !semesterOk && (
                    <ErrorRegion className="mt-1.5 text-xs text-red-600">
                      <span data-testid="enroll-semester-error">
                        That is not a semester id. It looks like
                        00000000-0000-0000-0000-000000000000 — ask your course staff for the
                        enrollment link.
                      </span>
                    </ErrorRegion>
                  )}
                </>
              )}
            </div>

            {failure !== null && (
              <ErrorRegion className="mt-4 rounded-lg border border-red-300 bg-red-50 p-4">
                <p className="text-sm font-semibold text-red-900" data-testid="enroll-error-title">
                  {failure.title}
                </p>
                <p className="mt-1 text-xs text-red-900" data-testid="enroll-error-detail">
                  {failure.detail}
                </p>
                {mint.error instanceof UnauthorizedError && (
                  <Link
                    to="/login?next=%2Fenroll"
                    className="mt-2 inline-block text-xs font-medium text-red-900 underline"
                    data-testid="enroll-error-signin"
                  >
                    Sign in again
                  </Link>
                )}
              </ErrorRegion>
            )}

            <button
              type="submit"
              disabled={mint.isPending || !semesterOk}
              data-testid="enroll-submit"
              className="mt-6 inline-flex w-full items-center justify-center rounded-md bg-orange-700 px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-orange-800 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-2 disabled:opacity-50"
            >
              {mint.isPending ? 'Issuing…' : 'Get my enrollment token'}
            </button>
            {mint.isPending && (
              <StatusRegion className="mt-2 text-center text-xs text-gray-500">
                Issuing your token…
              </StatusRegion>
            )}
          </form>
        )}

        <section className="mt-12 border-t border-gray-200 pt-6">
          <h2 className="text-sm font-semibold text-gray-900">Why it works this way</h2>
          <p className="mt-2 text-xs text-gray-600">
            Your recorder generates a key pair on your machine. The private half never leaves it —
            not to this page, not to the server, and there is no copy anywhere for anyone to lose or
            hand over. What you paste above is the public half; all the server does is sign a
            statement that this public key belongs to you in this course. That signed statement is
            the token.
          </p>
          <p className="mt-2 text-xs text-gray-600">
            Because there is no backup of your private key, moving to another machine means
            exporting your identity secret from the recorder — not asking anyone to reissue it for
            you.
          </p>
        </section>
      </div>
    </main>
  );
}
